### ISSUE TITLE
Verify validity of outputs

### ISSUE THREAD

**Issue by bangxiangyong** [Met4FoF/npl-jitter-noise-removal-mcmc#4]
Running the agents yielded the following graphs below

It would be good to validate/confirm whether these are the intended outputs ? (Mainly because graph 2 looks quite out of place to me)

![image](https://user-images.githubusercontent.com/8087472/116382555-f0a02380-a80d-11eb-9630-ba331182234c.png)

**Comment by BjoernLudwig** [comment]
I will request a screenshot of the expected outputs.

**Comment by BjoernLudwig** [comment]
The output is actually expected, as it resembles the screenshot provided by the authors, as can be seen here: https://github.com/Met4FoF/npl-jitter-noise-removal-mcmc/blob/main/GETSTARTED.md.
